// flow-typed signature: 276c6df4c2a4149c8e0881b1208e1d00
// flow-typed version: <<STUB>>/emotion-normalize_v10.1.0/flow_v0.100.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'emotion-normalize'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'emotion-normalize' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'emotion-normalize/dist/index' {
  declare module.exports: any;
}

declare module 'emotion-normalize/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'emotion-normalize/dist/index.js' {
  declare module.exports: $Exports<'emotion-normalize/dist/index'>;
}
declare module 'emotion-normalize/src/index.js' {
  declare module.exports: $Exports<'emotion-normalize/src/index'>;
}
