// flow-typed signature: bdbe1bf3e15bdebc290f8cec698b9a83
// flow-typed version: <<STUB>>/eslint-import-resolver-webpack_v0.11.1/flow_v0.100.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-import-resolver-webpack'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-import-resolver-webpack' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-import-resolver-webpack/config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-import-resolver-webpack/config.js' {
  declare module.exports: $Exports<'eslint-import-resolver-webpack/config'>;
}
declare module 'eslint-import-resolver-webpack/index' {
  declare module.exports: $Exports<'eslint-import-resolver-webpack'>;
}
declare module 'eslint-import-resolver-webpack/index.js' {
  declare module.exports: $Exports<'eslint-import-resolver-webpack'>;
}
