// flow-typed signature: b73a7ab3bc1b89701c9be7d951ece5a7
// flow-typed version: <<STUB>>/null-loader_v3.0.0/flow_v0.100.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'null-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'null-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'null-loader/dist/cjs' {
  declare module.exports: any;
}

declare module 'null-loader/dist/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'null-loader/dist/cjs.js' {
  declare module.exports: $Exports<'null-loader/dist/cjs'>;
}
declare module 'null-loader/dist/index.js' {
  declare module.exports: $Exports<'null-loader/dist/index'>;
}
