// flow-typed signature: 26690f81f993b51651e6268a4031635e
// flow-typed version: <<STUB>>/react-cookie-consent_v3.0.0/flow_v0.115.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-cookie-consent'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-cookie-consent' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-cookie-consent/build' {
  declare module.exports: any;
}

declare module 'react-cookie-consent/src' {
  declare module.exports: any;
}

declare module 'react-cookie-consent/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-cookie-consent/build/index' {
  declare module.exports: $Exports<'react-cookie-consent/build'>;
}
declare module 'react-cookie-consent/build/index.js' {
  declare module.exports: $Exports<'react-cookie-consent/build'>;
}
declare module 'react-cookie-consent/src/index' {
  declare module.exports: $Exports<'react-cookie-consent/src'>;
}
declare module 'react-cookie-consent/src/index.js' {
  declare module.exports: $Exports<'react-cookie-consent/src'>;
}
declare module 'react-cookie-consent/webpack.config.js' {
  declare module.exports: $Exports<'react-cookie-consent/webpack.config'>;
}
