// flow-typed signature: 4f9c91d4acd91e4a68876b87dc98240f
// flow-typed version: <<STUB>>/react-hooks-testing-library_v0.5.1/flow_v0.100.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-hooks-testing-library'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-hooks-testing-library' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-hooks-testing-library/lib/index' {
  declare module.exports: any;
}

declare module 'react-hooks-testing-library/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-hooks-testing-library/lib/index.js' {
  declare module.exports: $Exports<'react-hooks-testing-library/lib/index'>;
}
declare module 'react-hooks-testing-library/src/index.js' {
  declare module.exports: $Exports<'react-hooks-testing-library/src/index'>;
}
