// flow-typed signature: 4201b5986107561842ad9481cf60057d
// flow-typed version: <<STUB>>/react-social-icons_v4.1.0/flow_v0.116.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-social-icons'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-social-icons' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-social-icons/dist/_networks-db' {
  declare module.exports: any;
}

declare module 'react-social-icons/dist/app.95611b6d' {
  declare module.exports: any;
}

declare module 'react-social-icons/dist/app.ae05fb60' {
  declare module.exports: any;
}

declare module 'react-social-icons/dist/app.c328ef1a' {
  declare module.exports: any;
}

declare module 'react-social-icons/dist/background' {
  declare module.exports: any;
}

declare module 'react-social-icons/dist/icon' {
  declare module.exports: any;
}

declare module 'react-social-icons/dist' {
  declare module.exports: any;
}

declare module 'react-social-icons/dist/mask' {
  declare module.exports: any;
}

declare module 'react-social-icons/dist/networks' {
  declare module.exports: any;
}

declare module 'react-social-icons/dist/react-social-icons' {
  declare module.exports: any;
}

declare module 'react-social-icons/dist/social-icon' {
  declare module.exports: any;
}

declare module 'react-social-icons/dist/styles' {
  declare module.exports: any;
}

declare module 'react-social-icons/dist/symbols' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-social-icons/dist/_networks-db.js' {
  declare module.exports: $Exports<'react-social-icons/dist/_networks-db'>;
}
declare module 'react-social-icons/dist/app.95611b6d.js' {
  declare module.exports: $Exports<'react-social-icons/dist/app.95611b6d'>;
}
declare module 'react-social-icons/dist/app.ae05fb60.js' {
  declare module.exports: $Exports<'react-social-icons/dist/app.ae05fb60'>;
}
declare module 'react-social-icons/dist/app.c328ef1a.js' {
  declare module.exports: $Exports<'react-social-icons/dist/app.c328ef1a'>;
}
declare module 'react-social-icons/dist/background.js' {
  declare module.exports: $Exports<'react-social-icons/dist/background'>;
}
declare module 'react-social-icons/dist/icon.js' {
  declare module.exports: $Exports<'react-social-icons/dist/icon'>;
}
declare module 'react-social-icons/dist/index' {
  declare module.exports: $Exports<'react-social-icons/dist'>;
}
declare module 'react-social-icons/dist/index.js' {
  declare module.exports: $Exports<'react-social-icons/dist'>;
}
declare module 'react-social-icons/dist/mask.js' {
  declare module.exports: $Exports<'react-social-icons/dist/mask'>;
}
declare module 'react-social-icons/dist/networks.js' {
  declare module.exports: $Exports<'react-social-icons/dist/networks'>;
}
declare module 'react-social-icons/dist/react-social-icons.js' {
  declare module.exports: $Exports<'react-social-icons/dist/react-social-icons'>;
}
declare module 'react-social-icons/dist/social-icon.js' {
  declare module.exports: $Exports<'react-social-icons/dist/social-icon'>;
}
declare module 'react-social-icons/dist/styles.js' {
  declare module.exports: $Exports<'react-social-icons/dist/styles'>;
}
declare module 'react-social-icons/dist/symbols.js' {
  declare module.exports: $Exports<'react-social-icons/dist/symbols'>;
}
