// flow-typed signature: 32aa87a4c66a7a5dad2b32fa887c2c86
// flow-typed version: <<STUB>>/react-lazy-load-image-component_v1.4.0/flow_v0.115.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-lazy-load-image-component'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-lazy-load-image-component' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-lazy-load-image-component/build' {
  declare module.exports: any;
}

declare module 'react-lazy-load-image-component/src/components/LazyLoadComponent' {
  declare module.exports: any;
}

declare module 'react-lazy-load-image-component/src/components/LazyLoadComponent.spec' {
  declare module.exports: any;
}

declare module 'react-lazy-load-image-component/src/components/LazyLoadImage' {
  declare module.exports: any;
}

declare module 'react-lazy-load-image-component/src/components/LazyLoadImage.spec' {
  declare module.exports: any;
}

declare module 'react-lazy-load-image-component/src/components/PlaceholderWithoutTracking' {
  declare module.exports: any;
}

declare module 'react-lazy-load-image-component/src/components/PlaceholderWithoutTracking.spec' {
  declare module.exports: any;
}

declare module 'react-lazy-load-image-component/src/components/PlaceholderWithTracking' {
  declare module.exports: any;
}

declare module 'react-lazy-load-image-component/src/hoc/trackWindowScroll' {
  declare module.exports: any;
}

declare module 'react-lazy-load-image-component/src' {
  declare module.exports: any;
}

declare module 'react-lazy-load-image-component/src/utils/get-scroll-element' {
  declare module.exports: any;
}

declare module 'react-lazy-load-image-component/src/utils/intersection-observer' {
  declare module.exports: any;
}

declare module 'react-lazy-load-image-component/src/utils/intersection-observer.spec' {
  declare module.exports: any;
}

declare module 'react-lazy-load-image-component/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-lazy-load-image-component/build/index' {
  declare module.exports: $Exports<'react-lazy-load-image-component/build'>;
}
declare module 'react-lazy-load-image-component/build/index.js' {
  declare module.exports: $Exports<'react-lazy-load-image-component/build'>;
}
declare module 'react-lazy-load-image-component/src/components/LazyLoadComponent.jsx' {
  declare module.exports: $Exports<'react-lazy-load-image-component/src/components/LazyLoadComponent'>;
}
declare module 'react-lazy-load-image-component/src/components/LazyLoadComponent.spec.js' {
  declare module.exports: $Exports<'react-lazy-load-image-component/src/components/LazyLoadComponent.spec'>;
}
declare module 'react-lazy-load-image-component/src/components/LazyLoadImage.jsx' {
  declare module.exports: $Exports<'react-lazy-load-image-component/src/components/LazyLoadImage'>;
}
declare module 'react-lazy-load-image-component/src/components/LazyLoadImage.spec.js' {
  declare module.exports: $Exports<'react-lazy-load-image-component/src/components/LazyLoadImage.spec'>;
}
declare module 'react-lazy-load-image-component/src/components/PlaceholderWithoutTracking.jsx' {
  declare module.exports: $Exports<'react-lazy-load-image-component/src/components/PlaceholderWithoutTracking'>;
}
declare module 'react-lazy-load-image-component/src/components/PlaceholderWithoutTracking.spec.js' {
  declare module.exports: $Exports<'react-lazy-load-image-component/src/components/PlaceholderWithoutTracking.spec'>;
}
declare module 'react-lazy-load-image-component/src/components/PlaceholderWithTracking.jsx' {
  declare module.exports: $Exports<'react-lazy-load-image-component/src/components/PlaceholderWithTracking'>;
}
declare module 'react-lazy-load-image-component/src/hoc/trackWindowScroll.js' {
  declare module.exports: $Exports<'react-lazy-load-image-component/src/hoc/trackWindowScroll'>;
}
declare module 'react-lazy-load-image-component/src/index' {
  declare module.exports: $Exports<'react-lazy-load-image-component/src'>;
}
declare module 'react-lazy-load-image-component/src/index.js' {
  declare module.exports: $Exports<'react-lazy-load-image-component/src'>;
}
declare module 'react-lazy-load-image-component/src/utils/get-scroll-element.js' {
  declare module.exports: $Exports<'react-lazy-load-image-component/src/utils/get-scroll-element'>;
}
declare module 'react-lazy-load-image-component/src/utils/intersection-observer.js' {
  declare module.exports: $Exports<'react-lazy-load-image-component/src/utils/intersection-observer'>;
}
declare module 'react-lazy-load-image-component/src/utils/intersection-observer.spec.js' {
  declare module.exports: $Exports<'react-lazy-load-image-component/src/utils/intersection-observer.spec'>;
}
declare module 'react-lazy-load-image-component/webpack.config.js' {
  declare module.exports: $Exports<'react-lazy-load-image-component/webpack.config'>;
}
