// flow-typed signature: d453cdc0ed8ae2b666f08e322af9a6bb
// flow-typed version: <<STUB>>/react-intersection-observer_v8.25.2/flow_v0.116.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-intersection-observer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-intersection-observer' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-intersection-observer/react-intersection-observer.cjs' {
  declare module.exports: any;
}

declare module 'react-intersection-observer/react-intersection-observer.esm' {
  declare module.exports: any;
}

declare module 'react-intersection-observer/react-intersection-observer.umd.min' {
  declare module.exports: any;
}

declare module 'react-intersection-observer/test-utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-intersection-observer/react-intersection-observer.cjs.js' {
  declare module.exports: $Exports<'react-intersection-observer/react-intersection-observer.cjs'>;
}
declare module 'react-intersection-observer/react-intersection-observer.esm.js' {
  declare module.exports: $Exports<'react-intersection-observer/react-intersection-observer.esm'>;
}
declare module 'react-intersection-observer/react-intersection-observer.umd.min.js' {
  declare module.exports: $Exports<'react-intersection-observer/react-intersection-observer.umd.min'>;
}
declare module 'react-intersection-observer/test-utils.js' {
  declare module.exports: $Exports<'react-intersection-observer/test-utils'>;
}
