// flow-typed signature: 7e4c0884f21f7e1075eda011219f705a
// flow-typed version: <<STUB>>/react-images_v1.1.0-beta.1/flow_v0.115.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-images'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-images' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-images/dist/react-images.es' {
  declare module.exports: any;
}

declare module 'react-images/dist/react-images' {
  declare module.exports: any;
}

declare module 'react-images/dist/react-images.min' {
  declare module.exports: any;
}

declare module 'react-images/lib/components/Carousel' {
  declare module.exports: any;
}

declare module 'react-images/lib/components/component-helpers' {
  declare module.exports: any;
}

declare module 'react-images/lib/components/Container' {
  declare module.exports: any;
}

declare module 'react-images/lib/components/css-helpers' {
  declare module.exports: any;
}

declare module 'react-images/lib/components/defaultComponents' {
  declare module.exports: any;
}

declare module 'react-images/lib/components/Footer' {
  declare module.exports: any;
}

declare module 'react-images/lib/components/Header' {
  declare module.exports: any;
}

declare module 'react-images/lib/components' {
  declare module.exports: any;
}

declare module 'react-images/lib/components/Modal/Animation' {
  declare module.exports: any;
}

declare module 'react-images/lib/components/Modal/Gateway' {
  declare module.exports: any;
}

declare module 'react-images/lib/components/Modal' {
  declare module.exports: any;
}

declare module 'react-images/lib/components/Modal/Modal' {
  declare module.exports: any;
}

declare module 'react-images/lib/components/Modal/styled' {
  declare module.exports: any;
}

declare module 'react-images/lib/components/Navigation' {
  declare module.exports: any;
}

declare module 'react-images/lib/components/Portal' {
  declare module.exports: any;
}

declare module 'react-images/lib/components/Spinner' {
  declare module.exports: any;
}

declare module 'react-images/lib/components/svg' {
  declare module.exports: any;
}

declare module 'react-images/lib/components/View' {
  declare module.exports: any;
}

declare module 'react-images/lib/formatters' {
  declare module.exports: any;
}

declare module 'react-images/lib' {
  declare module.exports: any;
}

declare module 'react-images/lib/index.umd' {
  declare module.exports: any;
}

declare module 'react-images/lib/primitives' {
  declare module.exports: any;
}

declare module 'react-images/lib/styles' {
  declare module.exports: any;
}

declare module 'react-images/lib/types' {
  declare module.exports: any;
}

declare module 'react-images/lib/utils' {
  declare module.exports: any;
}

declare module 'react-images/src/components/Carousel' {
  declare module.exports: any;
}

declare module 'react-images/src/components/component-helpers' {
  declare module.exports: any;
}

declare module 'react-images/src/components/Container' {
  declare module.exports: any;
}

declare module 'react-images/src/components/css-helpers' {
  declare module.exports: any;
}

declare module 'react-images/src/components/defaultComponents' {
  declare module.exports: any;
}

declare module 'react-images/src/components/Footer' {
  declare module.exports: any;
}

declare module 'react-images/src/components/Header' {
  declare module.exports: any;
}

declare module 'react-images/src/components' {
  declare module.exports: any;
}

declare module 'react-images/src/components/Modal/Animation' {
  declare module.exports: any;
}

declare module 'react-images/src/components/Modal/Gateway' {
  declare module.exports: any;
}

declare module 'react-images/src/components/Modal' {
  declare module.exports: any;
}

declare module 'react-images/src/components/Modal/Modal' {
  declare module.exports: any;
}

declare module 'react-images/src/components/Modal/styled' {
  declare module.exports: any;
}

declare module 'react-images/src/components/Navigation' {
  declare module.exports: any;
}

declare module 'react-images/src/components/Portal' {
  declare module.exports: any;
}

declare module 'react-images/src/components/Spinner' {
  declare module.exports: any;
}

declare module 'react-images/src/components/svg' {
  declare module.exports: any;
}

declare module 'react-images/src/components/View' {
  declare module.exports: any;
}

declare module 'react-images/src/formatters' {
  declare module.exports: any;
}

declare module 'react-images/src' {
  declare module.exports: any;
}

declare module 'react-images/src/index.umd' {
  declare module.exports: any;
}

declare module 'react-images/src/primitives' {
  declare module.exports: any;
}

declare module 'react-images/src/styles' {
  declare module.exports: any;
}

declare module 'react-images/src/types' {
  declare module.exports: any;
}

declare module 'react-images/src/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-images/dist/react-images.es.js' {
  declare module.exports: $Exports<'react-images/dist/react-images.es'>;
}
declare module 'react-images/dist/react-images.js' {
  declare module.exports: $Exports<'react-images/dist/react-images'>;
}
declare module 'react-images/dist/react-images.min.js' {
  declare module.exports: $Exports<'react-images/dist/react-images.min'>;
}
declare module 'react-images/lib/components/Carousel.js' {
  declare module.exports: $Exports<'react-images/lib/components/Carousel'>;
}
declare module 'react-images/lib/components/component-helpers.js' {
  declare module.exports: $Exports<'react-images/lib/components/component-helpers'>;
}
declare module 'react-images/lib/components/Container.js' {
  declare module.exports: $Exports<'react-images/lib/components/Container'>;
}
declare module 'react-images/lib/components/css-helpers.js' {
  declare module.exports: $Exports<'react-images/lib/components/css-helpers'>;
}
declare module 'react-images/lib/components/defaultComponents.js' {
  declare module.exports: $Exports<'react-images/lib/components/defaultComponents'>;
}
declare module 'react-images/lib/components/Footer.js' {
  declare module.exports: $Exports<'react-images/lib/components/Footer'>;
}
declare module 'react-images/lib/components/Header.js' {
  declare module.exports: $Exports<'react-images/lib/components/Header'>;
}
declare module 'react-images/lib/components/index' {
  declare module.exports: $Exports<'react-images/lib/components'>;
}
declare module 'react-images/lib/components/index.js' {
  declare module.exports: $Exports<'react-images/lib/components'>;
}
declare module 'react-images/lib/components/Modal/Animation.js' {
  declare module.exports: $Exports<'react-images/lib/components/Modal/Animation'>;
}
declare module 'react-images/lib/components/Modal/Gateway.js' {
  declare module.exports: $Exports<'react-images/lib/components/Modal/Gateway'>;
}
declare module 'react-images/lib/components/Modal/index' {
  declare module.exports: $Exports<'react-images/lib/components/Modal'>;
}
declare module 'react-images/lib/components/Modal/index.js' {
  declare module.exports: $Exports<'react-images/lib/components/Modal'>;
}
declare module 'react-images/lib/components/Modal/Modal.js' {
  declare module.exports: $Exports<'react-images/lib/components/Modal/Modal'>;
}
declare module 'react-images/lib/components/Modal/styled.js' {
  declare module.exports: $Exports<'react-images/lib/components/Modal/styled'>;
}
declare module 'react-images/lib/components/Navigation.js' {
  declare module.exports: $Exports<'react-images/lib/components/Navigation'>;
}
declare module 'react-images/lib/components/Portal.js' {
  declare module.exports: $Exports<'react-images/lib/components/Portal'>;
}
declare module 'react-images/lib/components/Spinner.js' {
  declare module.exports: $Exports<'react-images/lib/components/Spinner'>;
}
declare module 'react-images/lib/components/svg.js' {
  declare module.exports: $Exports<'react-images/lib/components/svg'>;
}
declare module 'react-images/lib/components/View.js' {
  declare module.exports: $Exports<'react-images/lib/components/View'>;
}
declare module 'react-images/lib/formatters.js' {
  declare module.exports: $Exports<'react-images/lib/formatters'>;
}
declare module 'react-images/lib/index' {
  declare module.exports: $Exports<'react-images/lib'>;
}
declare module 'react-images/lib/index.js' {
  declare module.exports: $Exports<'react-images/lib'>;
}
declare module 'react-images/lib/index.umd.js' {
  declare module.exports: $Exports<'react-images/lib/index.umd'>;
}
declare module 'react-images/lib/primitives.js' {
  declare module.exports: $Exports<'react-images/lib/primitives'>;
}
declare module 'react-images/lib/styles.js' {
  declare module.exports: $Exports<'react-images/lib/styles'>;
}
declare module 'react-images/lib/types.js' {
  declare module.exports: $Exports<'react-images/lib/types'>;
}
declare module 'react-images/lib/utils.js' {
  declare module.exports: $Exports<'react-images/lib/utils'>;
}
declare module 'react-images/src/components/Carousel.js' {
  declare module.exports: $Exports<'react-images/src/components/Carousel'>;
}
declare module 'react-images/src/components/component-helpers.js' {
  declare module.exports: $Exports<'react-images/src/components/component-helpers'>;
}
declare module 'react-images/src/components/Container.js' {
  declare module.exports: $Exports<'react-images/src/components/Container'>;
}
declare module 'react-images/src/components/css-helpers.js' {
  declare module.exports: $Exports<'react-images/src/components/css-helpers'>;
}
declare module 'react-images/src/components/defaultComponents.js' {
  declare module.exports: $Exports<'react-images/src/components/defaultComponents'>;
}
declare module 'react-images/src/components/Footer.js' {
  declare module.exports: $Exports<'react-images/src/components/Footer'>;
}
declare module 'react-images/src/components/Header.js' {
  declare module.exports: $Exports<'react-images/src/components/Header'>;
}
declare module 'react-images/src/components/index' {
  declare module.exports: $Exports<'react-images/src/components'>;
}
declare module 'react-images/src/components/index.js' {
  declare module.exports: $Exports<'react-images/src/components'>;
}
declare module 'react-images/src/components/Modal/Animation.js' {
  declare module.exports: $Exports<'react-images/src/components/Modal/Animation'>;
}
declare module 'react-images/src/components/Modal/Gateway.js' {
  declare module.exports: $Exports<'react-images/src/components/Modal/Gateway'>;
}
declare module 'react-images/src/components/Modal/index' {
  declare module.exports: $Exports<'react-images/src/components/Modal'>;
}
declare module 'react-images/src/components/Modal/index.js' {
  declare module.exports: $Exports<'react-images/src/components/Modal'>;
}
declare module 'react-images/src/components/Modal/Modal.js' {
  declare module.exports: $Exports<'react-images/src/components/Modal/Modal'>;
}
declare module 'react-images/src/components/Modal/styled.js' {
  declare module.exports: $Exports<'react-images/src/components/Modal/styled'>;
}
declare module 'react-images/src/components/Navigation.js' {
  declare module.exports: $Exports<'react-images/src/components/Navigation'>;
}
declare module 'react-images/src/components/Portal.js' {
  declare module.exports: $Exports<'react-images/src/components/Portal'>;
}
declare module 'react-images/src/components/Spinner.js' {
  declare module.exports: $Exports<'react-images/src/components/Spinner'>;
}
declare module 'react-images/src/components/svg.js' {
  declare module.exports: $Exports<'react-images/src/components/svg'>;
}
declare module 'react-images/src/components/View.js' {
  declare module.exports: $Exports<'react-images/src/components/View'>;
}
declare module 'react-images/src/formatters.js' {
  declare module.exports: $Exports<'react-images/src/formatters'>;
}
declare module 'react-images/src/index' {
  declare module.exports: $Exports<'react-images/src'>;
}
declare module 'react-images/src/index.js' {
  declare module.exports: $Exports<'react-images/src'>;
}
declare module 'react-images/src/index.umd.js' {
  declare module.exports: $Exports<'react-images/src/index.umd'>;
}
declare module 'react-images/src/primitives.js' {
  declare module.exports: $Exports<'react-images/src/primitives'>;
}
declare module 'react-images/src/styles.js' {
  declare module.exports: $Exports<'react-images/src/styles'>;
}
declare module 'react-images/src/types.js' {
  declare module.exports: $Exports<'react-images/src/types'>;
}
declare module 'react-images/src/utils.js' {
  declare module.exports: $Exports<'react-images/src/utils'>;
}
